### ISSUE TITLE
Vim 版本介绍

### ISSUE THREAD

**Issue by Mayrixon** [vim-china/hello-vim#16]
是否应该简单介绍一下Vim、GVim、NeoVim之间的区别，以及Vim 7.4之前和Vim 8.0之后的区别？另外，是否应该让大家注意一下Vim各版本的patches，因为这会关系到系统clipboard能否正常使用

**Comment by Ding-Fan** [comment]
建议在介绍各版本的同时，给出一个面向有选择困难症的新手的当前推荐版本。

**Comment by izhengfan** [comment]
关于版本、安装方式之类的具体信息，感觉不必放在主文档下。主文档介绍 Vim 最核心的概念和操作，各个进阶话题则各自独立成一个 md 文件，从主文档链接过去即可。

**Comment by wsdjeg** [comment]
参阅 https://github.com/vim-china/vim-china.github.io/issues/7
