### ISSUE TITLE
如何管理你的 dotfile

### ISSUE THREAD

**Issue by Ding-Fan** [vim-china/hello-vim#19]
介绍 dotfile 是什么，如何用 git 来管理自己的 dotfile 等
参考：[dotfiles新手教程](https://luolei.org/dotfiles-tutorial/)

**Comment by Mayrixon** [comment]
我建议可以把这个链接放入正文，但不应介绍太多。这个项目的目的是 Vim 入门，而不是 *nix 系统配置入门

**Comment by wsdjeg** [comment]
这毕竟是 Vim 教材，我可能会倾向于写一篇，如何管理 Vim 配置文件的教程，这将更加切合主题。
