### ISSUE TITLE
快速上手常用配置、插件

### ISSUE THREAD

**Issue by Ding-Fan** [vim-china/hello-vim#20]
如何针对前、后端开发及不同语言搭建自己的 vim ，先让用户把 vim 用起来。
对于 vscode 用户，推荐 https://github.com/VSCodeVim/Vim 
对于 mac 用户，推荐 https://pqrs.org/osx/karabiner ，可以把任意按键，例如 <kbd>caps lock</kbd> ，设为 <kbd>esc</kbd> 。保护小指从现在开始。

**Comment by wsdjeg** [comment]
为了集中讨论，请将此issue移植到 https://github.com/vim-china/vim-china.github.io 感谢！
