### ISSUE TITLE
请问如何把@/转成原意的文本？

### ISSUE THREAD

**Issue by hyaray** [vim-china/hello-vim#23]
我想删除@/的相关修饰内容，获取原文本。
比如用默认的*键搜索当前单词abc，@/=\<abc\>，结果=abc
如果@/=\v<abc>，结果=abc
比如@/=m-\\，结果=m-\
不知道有没有人写过这个，求指点去哪寻找相关资源，谢谢

**Comment by wsdjeg** [comment]
没有明白你的具体需求，如果你需要搜索 `@/=<abc>` 这一串字符， 可以使用用：

```
/@\/=<abc>
```
